### ISSUE TITLE
MinimumSpan rule does not handle inverted axes correctly

### ISSUE THREAD

**Issue by manaruto** [ScottPlot/ScottPlot#4735]
```
signal.Data.Rotated = true;
myPlot.Axes.SetLimitsY(1000, 0);
```

The MinimumSpan rule does not work as expected because the Span property in the CoordinateRangeMutable class returns a negative value in the inverted state.

### Expected Behavior
The span should be handled correctly regardless of axis inversion.

### Current Behavior
The MinimumSpan rule  in the MinimumSpan class uses:

```
if (YAxis.Range.Span < YSpan)
{
    double yMin = YAxis.Range.Center - YSpan / 2;
    double yMax = YAxis.Range.Center + YSpan / 2;
    YAxis.Range.Set(yMin, yMax);
}
```

This fails when the axis is inverted, it overrides the axis limits, the user can not zoom in or out.

### Proposed Fix

Modify the code in MinimumSpan class as follows to handle the inverted axis correctly:

```
if (YAxis.IsInverted())
{
    if (Math.Abs(YAxis.Range.Span) < YSpan)
    {
        double yMin = YAxis.Range.Center - YSpan / 2;
        double yMax = YAxis.Range.Center + YSpan / 2;
        YAxis.Range.Set(yMax, yMin);
    }
}
else
{
    if (YAxis.Range.Span < YSpan)
    {
        double yMin = YAxis.Range.Center - YSpan / 2;
        double yMax = YAxis.Range.Center + YSpan / 2;
        YAxis.Range.Set(yMin, yMax);
    }
}
```

However, I am not sure if this is the best approach, or if it would be better to address the issue by modifying the Span property in the CoordinateRangeMutable class.

### Additional Considerations

The same issue applies to both X and Y axes, meaning fixes should be applied consistently to both dimensions.
The issue also affects the MaximumSpan rule, which should be adjusted similarly.

**ScottPlot Version: 5.053

**Comment by swharden** [comment]
Hi @manaruto, I think this may have been corrected in the most recent version (#4686, #4609) 

If the issue is present in the current version and your fix corrects the issue, can you create a pull request so I can merge in your code change? It looks like the proposed fix you offer will go here:

https://github.com/ScottPlot/ScottPlot/blob/fff3fca297c0e05c85e5dc19033504a3454605cf/src/ScottPlot5/ScottPlot5/AxisRules/MinimumSpan.cs#L11-L27

Thanks!
Scott

---

> it would be better to address the issue by modifying the Span property in the `CoordinateRangeMutable` class.

While true, I'd advise against modifying this behavior there because a lot of parts of the library depend on the present behavior of that class. I think making the fix in the axis rule itself is the best way to go.

**Comment by manaruto** [comment]
Hi Scott,

Thanks for your response! I appreciate the clarification regarding the Span property behavior.

The links you provided (#4686 and #4609) seem to be related to MinimumBoundary and MaximumBoundary rules, but the issue still persists in the MinimumSpan and MaximumSpan rules when the axis is inverted.

I have already created a pull request that fixes this issue. Let me know if any adjustments are needed. Thanks again!
